version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Mount the init.sql script

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  frontend:
    build: ./ui
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
